### PR TITLE
merge circular reveal fragment entry

### PR DESCRIPTION
**Pull request by ferdy182**
Added "Circular Reveal for Fragments" project entry in the file

### CODE REVIEW

**Comment by hborras** [comment]
Vamos a ponernos serios....

:-1: 

No está ordenado alfabeticamente dentro de la categoria :P

**Comment by ferdy182** [comment]
Reordered!

**Comment by hborras** [comment]
Esto es otra cosa!! jajaja

:+1:

**Comment by pedrovgs** [comment]
:+1:

**Comment by Aracem** [comment]
Thanks @plagueis for the detail about the alphabetical order. 
- Please in english :P

**Pull request merged**
