### PR TITLE
adding AndroidFillableLoaders to android-project-index.

### PR DESCRIPTION
**Pull request by JorgeCastilloPrz**
Add!

### CODE REVIEW

**Comment by pedrovgs** [comment]
Update your branch with master @JorgeCastilloPrz !

**Comment by JorgeCastilloPrz** [comment]
Ups. Sorry! :+1:

**Comment by lgvalle** [comment]
Watch out, you are committing  `README.md.orig`

**Comment by lgvalle** [comment]
:+1:

**Comment by pedrovgs** [comment]
:+1:

**Pull request merged**
