### PR TITLE
Add projects from github.com/pedrovgs account.

### PR DESCRIPTION
**Pull request by pedrovgs**
I've also added some missing dots at the end of the project description in projects already added. Please @Aracem, take a look :)

### CODE REVIEW

**Comment by lgvalle** [comment]
Very fine cinnamon :+1:

**Comment by Aracem** [comment]
I know that I am a fucking cabronazo but SMS should be placed above Storage :P

**Comment by Aracem** [comment]
Perfect Thanks!!! :+1:

**Comment by pedrovgs** [comment]
@Aracem done!

**Comment by Aracem** [comment]
Thanks @pedrovgs !!!

**Comment by pedrovgs** [comment]
You are welcome. Long live to FineCinnamon!!!

**Pull request merged**
