### PR TITLE
Added FABProgressCircle to User interface section.

### PR DESCRIPTION
**Pull request by JorgeCastilloPrz**
Added FABProgressCircle library to the readme user interface section. FABProgressCircle is an android library to provide a material progress circle around your FloatingActionButton. It is compatible with any existent FAB.

### CODE REVIEW

**Comment by mbarrben** [comment]
:+1:

**Comment by pedrovgs** [comment]
:+1:

**Comment by Aracem** [comment]
Very good! Nice Library :+1: :dancers:

**Comment by JorgeCastilloPrz** [comment]
Thanks ;)

**Pull request merged**
