### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sandeeplondhe**

### CODE REVIEW

**Comment by AnderWeb** [comment]
:+1:

**Comment by sandeeplondhe** [comment]
Hi fiend why that commit is not showing on original repository

**Comment by lgvalle** [comment]
Map v2? :-1:

**Comment by sandeeplondhe** [comment]
please talk in English , i don't understand symbolic language.

**Comment by CesarValiente** [comment]
None, Maps v2 nor Places give a real value to this index :-1:

**Comment by ffgiraldez** [comment]
should be great to update your project to AS and gradle build system, eclipse sucks

**Comment by Aracem** [comment]
-1
Several points:
- Is wrong formatted
- Is not sorted by alphabetial order
- I not see the utility of both libraries, they are simple tutorials
- Not in Android Studio

**Comment by sandeeplondhe** [comment]
okk will try to

**Comment by sandeeplondhe** [comment]
Android Studio is not everything, there are many ways to create build Android apps

**Comment by sandeeplondhe** [comment]
Android Studio Sucks

**Comment by Aracem** [comment]
Well that is your opinion, that it's ok, but:
- Is the official android IDE
- It uses gradle, the official build system
- It uses a better form to share libraries and mantain your code updated

**Comment by sandeeplondhe** [comment]
Yup I know, Still It Sucks.

**Comment by cesards** [comment]
:-1:

**Comment by Aracem** [comment]
Well :) I recommend you to try another time because AS >>>>>>>>>> Eclipse, but anyway, this is not the place to speak about that

Thank you

**Pull request closed without merging**
